# Site
repository: coluccigiovanni16/Know-Me
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Giovanni Colucci
title: Digital Cloud Developer - Consultant @ Deloitte Digital
email: coluccigiovanni16@gmail.com
website: coluccigiovanni16.github.io/Know-Me/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: coluccigio16
github_username:  coluccigiovanni16
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: coluccigiovanni16
# flickr_username: jekyll
instagram_username: coluccigiovanni16
linkedin_username: coluccigiovanni16
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Salesforce
  icon: fab fa-salesforce
  url: https://trailblazer.me/id/gcolucci16
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Giovanni and I'm a Digital Cloud Developer focused on Salesforce.
  As well as working in Salesforce project, I also have experience in Pytorch and Machine Learning on Graph.
  I am a dedicated, hard-working and proactive IT engineer with a strong background in back-end development
  and in the field of Machine Learning applied to the Health field thanks to my thesis periods in ENSICAEN
  and my master's degree in the University of Salerno. I have solid academic experience in the design, testing
  and analysis of software implementation processes to increase the overall efficiency of operations.
  Currently I am hired in Deloitte with the opportunity to work and attend the ‘Master in Digital Technology for Innovation’,
  I will take advantage of this opportunity to use my technical skills in a stimulating work environment and
  become a precious resource for the organization I work for.

  I am most skilled in: <mark>Salesforce Industries(old Vlocity)</mark> and <mark>Coding</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Deloitte Digital
        link: deloittedigital.com
        link_text: deloittedigital.com
        sub_title: Senior Salesforce Developer
        caption: March 2020 - Present
        quote: >
          Salesfoce Industries Addicted
        description: | # this will include new lines to allow paragraphs
            XXX

      - layout: left
        title: Greyc
        link: greyc.fr
        link_text: greyc.fr
        sub_title: Machine Learning Engineer
        caption: September 2020 - December 2020
        quote: >
          HEALTH INFORMATICS - Chemoinformatics and chemogenomics, medical data interpretation, health imaging, bioinformatics
        description: | # this will include new lines to allow paragraphs
            Implementation of Graph Machines using python, and their application to a dataset composed of molecule.

      - layout: left
        title: Genomix4life
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Full Stack Developer
        caption: September 2017 - December 2017
        quote: >
          Spin-off of the University of Salerno
        description: | # this will include new lines to allow paragraphs
          Create a site hosted in localhost to manage a DB of PCR summary file in order to compute complex searching and filtering on data.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Politecnico di Milano
        caption: 2020 - 2022
        sub_title: Master Universitario di 2° livello
        quote: >
          Digital Technologies for Innovation
        description: | # this will include new lines to allow paragraphs
          Parte Business --> Digital Business Models, Processes & Technologies;
          Parte Tech --> Continuous Integration, Developing for the cloud & The internet of services; Data modeling, Mobile Dev, Machine Learning, AI, UX/UI Design;
          Customer Relationship Management (CRM) --> Digital Platform studies , Salesforce Certifications.
          Metodologie --> Design Thinking, Agile;
          Soft Skills --> Time and change management, Leadership, People Management, Effective Communication.

      - layout: left
        title: Università degli Studi di Salerno
        caption: 2017 - 2019
        sub_title: Master's Degree In Computer Engineering
        quote: >
          BioInformatics and Digital Health
        description: | # this will include new lines to allow paragraphs
          XXX

      - layout: left
        title: Università degli Studi di Salerno
        caption: 2010 - 2016
        sub_title: Bachelor's Degree In Computer Engineering
        quote: >
          xx
        description: | # this will include new lines to allow paragraphs
          XX

  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Footbal
      - Bike
      - Dog


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
